version: "3.7"
services:
    db:
        container_name: 'db.desk'
        image: mariadb:10.8
        restart: unless-stopped
        volumes:
            - ${DB_DATA}:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=${DB_RANDOM_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        networks:
            - desk-networking

    phpmyadmin:
        container_name: 'myadmin.desk'
        image: phpmyadmin
        restart: unless-stopped
        environment:
            - PMA_HOST=db
        links:
            - db:db
        ports:
            - ${PHPMYADMIN_PORT}:80
        networks:
            - desk-networking

    app:
        user: "${UID}:${GID}"
        container_name: 'app.desk'
        build:
            context: ${PHP_DOCKERFILE_PATH}
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html
        image: travellist
        volumes:
            - ${APP_PATH}:/var/www/html
            - ${PHP_DOCKERFILE_PATH}/php.ini:/usr/local/etc/php/conf.d/desk.ini
        networks:
            - desk-networking

    nginx:
        container_name: 'web.desk'
        image: 'nginx:latest'
        restart: unless-stopped
        ports:
            - '${NGINX_HTTP_PORT}:80'
            - '${NGINX_HTTPS_PORT}:443'
        volumes:
            - ${NGINX_CONF_PATH}:/etc/nginx/conf.d:ro
            - ${APP_PATH}:/var/www/html
            - ${NGINX_LOG_PATH}:/var/log/nginx
            - ${NGINX_CERT_PATH}:/etc/nginx/certs
        networks:
            - desk-networking
        links:
            - app
        depends_on:
            - db
            - app
            - phpmyadmin

networks:
    desk-networking:
        driver: bridge
